### ISSUE TITLE
Cannot run with rector 0.19

### ISSUE THREAD

**Issue by wakoch** [Codito-Dev/rector-money#5]
Hello,

`ContainerConfigurator` is no longer used in rector. So how can I use rector-money with the return `RectorConfig::configure()` system? Or with the older `RectorConfig`?

**Comment by Wirone** [comment]
Hi @wakoch, it was only outdated readme, I've just pushed 4526aff8 with proper example, I also tested it in a simple reproducer repo with

```json
{
    "name": "codito/rector-money-test",
    "type": "project",
    "require": {
        "rector/rector": "^0.19",
        "codito/rector-money": "dev-main"
    }
}
```

and 

```php
<?php

use Rector\Config\RectorConfig;
use Codito\Rector\Money\MoneySetList;

return static function (RectorConfig $config): void {
    $config->import(MoneySetList::V4);

    $config->paths([
        __DIR__ . '/src',
    ]);
};
```

with a result:

```shell
 vendor/bin/rector
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
```

So it's possible to use this package with Rector 0.19 🙂. I will try to update the package to use Rector v1, but there are some weird errors currently when running `compose rector:check` on main branch:

```
 [ERROR] Could not process "tests/Rule/MultiplyAndDivideByStringRector/MultiplyAndDivideByStringRectorTest.php" file, due to: "Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getParamImmediatelyInvokedCallableTagValues()". On line: 307
```

Needs deeper investigation.

**Comment by Wirone** [comment]
Let me know if you have runtime errors too, not only related to config. I tested this on an empty file that did not trigger the rules from this repo, I was focused only on the config part 🙂.

**Comment by wakoch** [comment]
I downgraded rector and tried again. Unfortunately rector 0.19 is not running due to a phpstan error.

Thanks anyway!

**Comment by Wirone** [comment]
Rector requirement was bumped to `^1.0` in #6 and the problem disappeared. I am going to close this, let me know @wakoch if it works for you 🙂.

**Comment by wakoch** [comment]
Great, works now with current rector.
